version: "3"

services:   
  elasticsearch:
    image: bitnami/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_vol:/usr/share/elasticsearch/data
  
  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_vol:/data

  neo4j:
    image: neo4j:5.12.0
    container_name: neo4j
    environment:
      NEO4J_AUTH: none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_vol:/data
  
  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_vol:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  
  telegraf:
    image: telegraf:1.29.5-alpine
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./kafka/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin

  grafana:
    image: grafana/grafana:10.0.12-ubuntu
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_vol:/var/lib/grafana
      - ./kafka/grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres_vol:
  elasticsearch_vol:
  redis_vol:
  neo4j_vol:
  influxdb_vol:
  grafana_vol: